# roles/devbox/gitea.yml
services:
  gitea:
    image: gitea/gitea:1.25.2
    restart: unless-stopped
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__DOMAIN=${GITEA_FQDN}
      - GITEA__server__ROOT_URL=https://${GITEA_FQDN}/
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.rule=Host('${GITEA_FQDN}')
      - traefik.http.routers.gitea.entrypoints=websecure
      - traefik.http.routers.gitea.tls.certresolver=le
      - traefik.http.services.gitea.loadbalancer.server.port=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  gitea_data:
